# Generated by Django 4.1 on 2022-08-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(blank=True, max_length=90, null=True)),
                ('external_urls', models.JSONField(blank=True, default=dict, verbose_name='ExternalUrls')),
                ('followers', models.IntegerField()),
                ('images', models.JSONField(default=dict, verbose_name='Images')),
            ],
        ),
    ]
